# Generated by Django 5.2.8 on 2025-11-22 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_dest', to='core.location'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_source', to='core.location'),
        ),
        migrations.AddField(
            model_name='operationline',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.inventoryoperation'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Supplier or customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='core.partner'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='operationline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_as_dest', to='core.location'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.operationline'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.inventoryoperation'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.product'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_as_source', to='core.location'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.location'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'location')},
        ),
    ]
