# Generated by Django 5.2.8 on 2025-11-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Product cost per unit', max_digits=10),
        ),
    ]
